### PR TITLE
Linux build configuration fix. New script ./build-linux.sh

### PR DESCRIPTION
**Pull request by vitalfadeev**

### CODE REVIEW

**Comment by vitalfadeev** [comment]
https://forum.dlang.org/post/qmpjrzofoyzyyaughokz@forum.dlang.org

**Comment by DannyArends** [comment]
Hey @vitalfadeev ,

Thanks for contributing, 

I don't think that we need several .sh files to compile (since it's just dub compiling). If you feel strongly about having them they should go into a sh/ folder (which then complicates things since you'd be building from 1 folder down).

I don't think it's needed to create a separate configuration for linux, the preBuildCommands should just be split into windows and linux commands (preBuildCommands-windows and preBuildCommands-linux). I don't see any reason to duplicate the whole configuration just because of the prebuild commands. 

Ideally I would like to have the shaders compiled on runtime, comparable to how it is done with OpenGL shader compilation, but I haven't found a way to easily do that yet wit Vulkan.

**Comment by vitalfadeev** [comment]
Thank!
In futuree, when i asking working(!) example, you will give to me working example, please.

**Comment by DannyArends** [comment]
Just pushed a commit, to have the preBuildCommands being different for linux and windows, without needing to duplicate the whole configuration.

Could you check if this works for you ?

Danny

**Comment by DannyArends** [comment]
@vitalfadeev 

I had compiled it under linux before without any issues, you can never guarantee software works for every PC-configuration out there. 

Thanks for trying, could you let me know if the new dub.json works ?

**Comment by vitalfadeev** [comment]
Perfecto! 
Screenshot from 2021-07-12 20-19-25

Thanks!

**Comment by DannyArends** [comment]
Awesome !

If you want you can change your pull request to have 2 .sh files in an sh/ folder, as long as they're not in the root of the repository. 

I'm more than happy to have some .sh helper files in a separate folder.

Danny

**Comment by vitalfadeev** [comment]
```
# dub run -c android-64 --compiler=ldc2
Performing "debug" build using ldc2 for x86_64.
arsd-official:jni 9.5.0: building configuration "library"...
bindbc-loader 0.3.2: building configuration "yesBC"...
bindbc-sdl 0.21.4: building configuration "dynamicBC"...
calderad ~master: building configuration "android-64"...
Running pre-build commands...
src/physicaldevice.d(19,58): Deprecation: function erupted.types.VK_VERSION_MAJOR is deprecated - These defines have been derecated, use VK_MAKE_API_VERSION and VK_API_ variants instead!
src/physicaldevice.d(19,99): Deprecation: function erupted.types.VK_VERSION_MINOR is deprecated - These defines have been derecated, use VK_MAKE_API_VERSION and VK_API_ variants instead!
src/physicaldevice.d(19,140): Deprecation: function erupted.types.VK_VERSION_PATCH is deprecated - These defines have been derecated, use VK_MAKE_API_VERSION and VK_API_ variants instead!
Linking...
/usr/bin/ld.gold: error: cannot find -landroid
collect2: error: ld returned 1 exit status
Error: /usr/bin/cc failed with status: 1
ldc2 failed with exit code 1.
```

I got error when compilling for android-64 ( under linux ).
Not important today. 
Will used in future.
Thank, DannyArends !

**Comment by DannyArends** [comment]
No worries, which ldc2 compiler version are you using ? and did you install the ldc2 android libraries ?

See point2: 

_Download the LDC aarch64 library for Android file "ldc2-X.XX.X-android-aarch64.tar.xz" from https://github.com/ldc-developers/ldc/releases/ where X.XX.X is your LDC version and extract it_

**Pull request closed without merging**
